### PR TITLE
Lightbox for rich click-and-enlarge responsive images

### PR DESCRIPTION
**Pull request by torbjoernk**
For demo see page about 4th JLESC workshop in Bonn.

### CODE REVIEW

**Comment by torbjoernk** [comment]
It's ready.

**Comment by pancetta** [comment]
I get an 

> undefined method `destroy!' for nil:NilClass` 

during `Generating...`. Actually, it's

> Liquid Exception: undefined method `destroy!' for nil:NilClass in /Users/robert/Documents/JLESC-Website/_events_past/2015-12-02-4th-jlesc-workshop-bonn.md

**Comment by torbjoernk** [comment]
Would you mind rerunning jekyll with the additional parameter `--trace`? I guess it's a problem with your installed version of ImageMagick and/or GraphicsMagick. Either of them are now used to automatically resize and process the larger images when including with `{% lightbox_image ... %}`.

**Comment by pancetta** [comment]
Don't know what happened, but the error is gone...

**Comment by torbjoernk** [comment]
:smile: :+1:

**Pull request merged**
