### PR TITLE
Patch Alya

### PR DESCRIPTION
**Pull request by ramet**

### CODE REVIEW

**Comment by pancetta** [comment]
Sorry, it seems that I was to quick.. I already merged your first PR

**Comment by pancetta** [comment]
Are you going to cite the external references in the text? Let me know when you are done.

**Comment by ramet** [comment]
Can you told me how I can cite external references ?

**Comment by pancetta** [comment]
Have a look at e.g. the impact section in this project: https://github.com/JLESC/jlesc.github.io/blob/source/_projects/fmm_project.md#impact-and-publications

**Comment by pancetta** [comment]
For citing JLESC references (i.e. publications coming right from this project), see e.g. the impact section of this project: https://github.com/JLESC/jlesc.github.io/blob/source/_projects/Lossy_checkpoint_restart.md#impact-and-publications

**Comment by ramet** [comment]
Thanks. You can merge the PR if it's OK for you.

**Pull request merged**
