### PR TITLE
New Grant Page

### LINKED ISSUE #60: Fill "grants" page
Simply use http://publish.illinois.edu/jointlab-esc/grants/ to fill the "grants"-page in the "about"-tree.

### PR DESCRIPTION
**Pull request by isabelheisters**
So there are two examples.
The first one is a definition List. The second one a table.
Which one looks nicer?
I would prefer the second one. I think this is more clear. We could add the People from the People-Side too.
Fixes #60

### CODE REVIEW

**Comment by isabelheisters** [comment]
But maybe the scond one is more complex. So we should choose the first. I don't know.

**Comment by torbjoernk** [comment]
Thanks a lot for the showcase! A few points:
1. I don't think the table looks better. It's not responsive (i.e. it looks awful on small-screen devices). You might be able to improve a little bit by adding this line just before the table's header line:
   
   {:.table.table-hover.table-sm}
   
   Maybe you omit the last CSS class (the `.table-sm`).
   
   By the way: Why do you inject a third column in the middle?
2. You can improve the styling of the definition list a little further with some (S)CSS. Therefore, add `{:#grants}` just before the very first definition. Then, in `_assets/css/main.scss` you add the following somewhere in the `html { body { ... } }` section:
   
   ``` .scss
   dl#grants {
     dt {
       @extend .col-sm-12;
     }
     dd {
       @extend .col-sm-11;
       @extend .col-sm-offset-1;
     }
   }
   ```
3. In general, I'd suggest you style and separate the "_Leader for_" texts a little bit, e.g. italics. And maybe separate multiple leaders by newlines.
4. Try to use the `{% person ID %}` tags wherever possible :smiley:

**Comment by pancetta** [comment]
Yeah.. @torbjoernk screwed this one up. The PR is outdated.

**Comment by torbjoernk** [comment]
No, @pancetta, you screwed this up by merging my PRs before her's. :stuck_out_tongue_winking_eye: 

Anyway, @isabelheisters, you can fix this with a little bit of handwork:
1. copy the part of Sass you wrote to somewhere else (e.g. temporary file in editor)
2. checkout `source`, update it from upstream and go back to your feature branch
3. merge the `source` branch into your feature branch without committing (`git merge --no-ff --no-commit --log source`). Git will scream at you that there is a merge conflict in `_assets/css/main.scss`.
4. checkout `_assets/css/main.scss` from `source`: `git checkout source _assets/css/main.scss`
5. create a new Sass file for the grants page (`_assets/css/_grants.scss`), copy the content from the first step into that file and include it in the `main.scss` file, e.g. between the include of `projects` and `visits`
6. add everything (`git add -A`), finally commit the merge including your resolved merge conflict (`git commit --signoff`) and push it to this PR.

PS: Please, make sure you don't use tab stops for indentation.

**Comment by pancetta** [comment]
@isabelheisters No. 1! 1!

**Pull request merged**
