### PR TITLE
Update Blue Waters I/O traces project before closing

### PR DESCRIPTION
**Pull request by hephtaicie**

### CODE REVIEW

**Comment by pancetta** [comment]
You can now cite the papers here.

**Comment by hephtaicie** [comment]
I made an attempt. I hope that's the right way to do it.

**Comment by pancetta** [comment]
Are those external or JLESC publications?

**Comment by hephtaicie** [comment]
The two newly cited papers are JLESC papers. I'm moving them to `jlesc.bib` then. Good catch.

**Pull request merged**
