### PR TITLE
Feature/youthws

### PR DESCRIPTION
**Pull request by miwakotsuji**

### CODE REVIEW

**Review by pancetta — CHANGES_REQUESTED** [review]
Why do you need to add 'therubyracer' and why is the Gemfile.lock changed? This seems to be a simple news post only, right?

**Comment by miwakotsuji** [comment]
yes, this is a simple news post. I don't know why Gemfile.lock is changed..... muuu...

**Comment by pancetta** [comment]
Just get rid or (i.e. remove) the Gemfile and the Gemfile.lock in this commit and you're all set.

**Comment by miwakotsuji** [comment]
I've got it. I've added therubyracer just for my local test environment !and forgot to comment it out). I've commented  it out

**Review by pancetta — CHANGES_REQUESTED** [review]
Remove the Gemfile.lock, too, please.

**Pull request closed without merging**
