### PR TITLE
3rd JLESC Workshop Photos

### LINKED ISSUE #138: Put group photos on website
There are group photos for the BSC workshop. We should put them on the website as we did for the 4th workshop.

### PR DESCRIPTION
**Pull request by isabelheisters**
So I put the photos on the website. I think they are very large. Maybe we should move the session photo to the schedule site or we should make another site for the workshop programm?
Fixes #138
Signed-off-by: Isabel Heisters i.heisters@fz-juelich.de

### CODE REVIEW

**Comment by pancetta** [comment]
Indeed, these are very large. @torbjoernk How do we move the session photo to the html site without breaking the link? The first one can stay where it is.

**Comment by pancetta** [comment]
@isabelheisters We could put the first one to the very bottom of the page, so that is not in the way during reading.

**Comment by torbjoernk** [comment]
@isabelheisters, I've opened a PR on your feature branch fixing the positioning of the images and limiting their heights.

**Comment by pancetta** [comment]
I didn't know how to merge in this PR (in my case).. I just clicked on the "merge" link at Github, pulled the update to my local repository and pushed directly to source. That's not the way to go, I know, so what's the correct way of dealing with a PR on top of my own PR?

**Comment by torbjoernk** [comment]
Na, @pancetta, that's fine how you've done it. @isabelheisters _could_ merge my PR onto her's the same way you are merging regular PRs into `source`. That would be the _clean_ way. However, I'll stop nitpicking. She should just click on "merge pull request". That'll update her PR and you can merge her PR the way you always do it.

**Pull request merged**
