### PR TITLE
Update serghei-dmr.md with bib tex

### PR DESCRIPTION
**Pull request by siserte**

### CODE REVIEW

**Comment by siserte** [comment]
Hi,I do not why the link to https://jlesc.github.io/projects/serghei-dmr is broken from the post of the project. I’ve double-checked my md file and compared with others that work but I cannot find the error. When possible, could you have a look? Thank you! From: Robert SpeckSent: viernes, 5 de abril de 2024 11:59To: JLESC/jlesc.github.ioCc: Sergio Iserte; AuthorSubject: Re: [JLESC/jlesc.github.io] Update serghei-dmr.md with bib tex (PR #664) Merged #664 into source.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by siserte** [comment]
Please, ignore that email. In my last update I could solve it. Thank you From: Sergio IserteSent: lunes, 8 de abril de 2024 10:01To: JLESC/jlesc.github.io; JLESC/jlesc.github.ioCc: AuthorSubject: RE: [JLESC/jlesc.github.io] Update serghei-dmr.md with bib tex (PR #664) Hi,I do not why the link to https://jlesc.github.io/projects/serghei-dmr is broken from the post of the project. I’ve double-checked my md file and compared with others that work but I cannot find the error. When possible, could you have a look? Thank you! From: Robert SpeckSent: viernes, 5 de abril de 2024 11:59To: JLESC/jlesc.github.ioCc: Sergio Iserte; AuthorSubject: Re: [JLESC/jlesc.github.io] Update serghei-dmr.md with bib tex (PR #664) Merged #664 into source.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by pancetta** [comment]
I fixed it in my last commit, the problem was the wrong date (in the future).

**Comment by siserte** [comment]
Ah! I thought it was a wrong-formatted list. Thank you very much!   From: Robert SpeckSent: lunes, 8 de abril de 2024 10:03To: JLESC/jlesc.github.ioCc: Sergio Iserte; AuthorSubject: Re: [JLESC/jlesc.github.io] Update serghei-dmr.md with bib tex (PR #664) I fixed it in my last commit, the problem was the wrong date (in the future).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request merged**
