### PR TITLE
Update interop_chameleon_g5k.md

### PR DESCRIPTION
**Pull request by chr-perez**
Adding work done in 2016/17 related to Enos by Adrien's group.

### CODE REVIEW

**Comment by pancetta** [comment]
@krest I added a section on 2017/2018 to the text, is this ok? Check it out here: 
https://jlesc.github.io/projects/interop_chameleon_g5k/
We'd need this for the report.

**Comment by chr-perez** [comment]
Well, not really as the work was started in 2016. I am ok if we say 2016/2018.

In fact, I am not sure to understand what you exactly need for the report: a yearly based description of the work? a 2016/2017 section and a 2017/2018 section ?

**Comment by pancetta** [comment]
That'd be the optimal solution, very much as the other projects did. Any chance you can do something like this for your project?

**Comment by chr-perez** [comment]
Euh, what is the optimal solution? a yearly basis or a 2016/17 and 2017/18? Thanks!

**Comment by pancetta** [comment]
A 2016/2017 section and a 2017/2018 section would be best! Thanks!

**Pull request merged**
