### PR TITLE
Made first try of the about page.

### PR DESCRIPTION
**Pull request by isabelheisters**
Signed-off-by: Isabel Heisters i.heisters@fz-juelich.de

### CODE REVIEW

**Comment by torbjoernk** [comment]
Ok, a couple issues:
- [x] you entered a non-valid character, thus the file is now considered binary, which breaks diffing  
  (SmartGit tells me that it's in line 35, position 55)  
  try to delete that word "_other_" and type it again
- [x] don't indent the text paragraphs
- [x] do a line break after each (!) senctence
- [x] why is there an HTML comment (`<!--  -->`) in between?
- [x] why do you start with a 3rd level heading?

What editor are you using? vim? Kate? Either try to configure vim to show you the file type when editing or tell Kate to save as UTF-8.

After saving you can make sure its fixed by running `file` on the file: `file about/index.md`. It should tell you that it's an _UTF-8 encoded text_ and not _data_

**Comment by pancetta** [comment]
@torbjoernk Concerning the heading: I personally do not like the very, very large heading Markdown is producing on level 1 and 2, so I tend to use 3rd level headings, too.

**Comment by pancetta** [comment]
Also, I don't like the "About" on top of the page, directly followed by "What is JLESC?". Either we remove the "About: or the "What is JLESC?" (I guess, @torbjoernk prefers option no 2.).

**Comment by torbjoernk** [comment]
Well, the weight of the headings is something we can tweak with CSS. Let's fiddle with that in the office tomorrow, @pancetta.

The "About" heading is produced by Jekyll from the "title" field in the YAML header. I agree you drop "What is JLESC" and put it the "title" field directly.

**Comment by pancetta** [comment]
I'd just remove the "What is JLESC?" completely. "About" is a sufficient heading for this paragraph anyway. @isabelheisters could you correct that + the other issues @torbjoernk mentioned?

**Comment by isabelheisters** [comment]
Okay i will try to fix the problems as far as I can.

**Comment by isabelheisters** [comment]
What heading should I use? 1st or 3rd?

**Comment by torbjoernk** [comment]
Use 2nd as the the Jekyll-generated one is 1st.

**Comment by isabelheisters** [comment]
Can I replace the "About the Joint Lab" Maybe with "History of the Joint Lab" or something like this?

**Comment by pancetta** [comment]
Sure, sounds good! Change the text as much as you want and put it into a
pull requests. We'll complain afterwards anyway..

**Comment by isabelheisters** [comment]
So I have tried to correct the issues you mentioned, but I don't understand this one: don't indent the text paragraphs.

**Comment by torbjoernk** [comment]
You have 2 spaces in front of each line but the headings. You shouldn't.

**Comment by torbjoernk** [comment]
LGTM (looks good to me). :+1:

**Pull request merged**
