### PR TITLE
General improvements for TeX Report Generator

### PR DESCRIPTION
**Pull request by torbjoernk**
also adjusted heading levels of project files

ToDo:
- [X] adjust levels of headings
- [X] one file per topic gathering projects
- [x] adjust BibTeX includes (to work with multiple bib files)

### CODE REVIEW

**Comment by torbjoernk** [comment]
I'll add some documentation and then it's ready to be merged and used.

**Comment by pancetta** [comment]
I get a latex error:

> ! Undefined control sequence.
> <recently read> \tightlist 
> 
> l.10 \tightlist

Looks like this problem [here](http://tex.stackexchange.com/questions/257418/error-tightlist-converting-md-file-into-pdf-using-pandoc).

**Comment by torbjoernk** [comment]
Ok, probably need to ship Pandoc's `writer.latex` file with our generator. :cry:

**Comment by torbjoernk** [comment]
@pancetta Try if that works.

**Comment by pancetta** [comment]
Getting (much) closer. `latexmk` does the trick now, but the tables are messed up in the resulting pdf.

**Comment by pancetta** [comment]
@torbjoernk: aaaahhh... conflicts!

**Comment by pancetta** [comment]
And here we go again:

> ! Undefined control sequence.
> l.5 ...graph{Research topic and goals}\hypertarget
>                                                   {research-topic-and-goals}...

What now?

**Comment by torbjoernk** [comment]
Yeah, `hyperref` package. And a few more things are broken. :-/

**Comment by torbjoernk** [comment]
There are still some encoding issues with the weblinks. I'll look into that tomorrow.

**Comment by pancetta** [comment]
Even closer! Compiles, tables look good, check! But there are some weird spaces in the document, e.g. after the "some text" and before the first project (see e.g. page 3). Also, in page 8 something is going wrong.

**Comment by pancetta** [comment]
How about citation of URLs...? I know, I know..

**Comment by torbjoernk** [comment]
Make sure, they are not used as references in the project itself. Websites should be linked, not referenced.

**Comment by pancetta** [comment]
Na, I don't agree. Links in the text are bad for the reader (if anyone dares to read this, anyway). So, I prefer websites as references.. sorry.

**Pull request merged**
