### PR TITLE
Fmm project

### PR DESCRIPTION
**Pull request by ivokabadshow**
Two times a charm?

### CODE REVIEW

**Comment by pancetta** [comment]
I don't get it: why are there so many commits in this PR? Did you start with a clean clone..?

**Comment by ivokabadshow** [comment]
Yep. Removed my local branch completely and re-did everything. What did you expect? There are no issues ... Don't know, what it should look like. Since the last merge from our branch other stuff changed as well, which I had to import. Didn't the other have a similar "merge layout"?

**Comment by pancetta** [comment]
Just wondering.. look at e.g. PR #193. This is how a clean PR should look like. Am I missing something here?

**Comment by torbjoernk** [comment]
@ivokabadshow, you somehow managed to merge in the commits from the `master` branch into your branch and the `source` branch. The `source` branch and `master` branch are orphan to each other.

Please, follow the steps described in the wiki on how to start setting up a local working copy and make sure, you branch your feature branch off from `source` and not `master`!

**Pull request closed without merging**
